name: multitrackpy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - tqdm
  - h5py
  - imageio
  - scikit-image
  - pip
  - pip:
    - bbo-multitrackpy
    - bbo-calibcamlib
    - bbo-ccvtools
    - bbo-bbo
    - matplotlib
    - construct
