name: multitrackpy
channels:
  - open3d-admin
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - tqdm
  - h5py
  - imageio
  - scikit-image
  - pip
  - pip:
    - bbo-ccvtools
    - construct
